# Generated by Django 4.2.10 on 2024-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_shoppingcart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
