# Generated by Django 4.2.10 on 2024-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_alter_shoppingcart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='session_key',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
