# Generated by Django 4.2.10 on 2024-02-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='metal',
            options={'verbose_name_plural': 'Metals'},
        ),
    ]
